_format_version: "3.0"
_transform: true

services:
  - name: auth
    url: http://host.docker.internal:3001
    routes:
      - name: auth-route
        paths:
          - /api/auth
        strip_path: false

  - name: profile
    url: http://host.docker.internal:3002
    routes:
      - name: profile-route
        paths:
          - /api/profile
        strip_path: false

  - name: search
    url: http://host.docker.internal:3003
    routes:
      - name: search-route
        paths:
          - /api/search
        strip_path: false

  - name: catalog
    url: http://host.docker.internal:3004
    routes:
      - name: catalog-route
        paths:
          - /api/catalog
        strip_path: false

  - name: booking
    url: http://host.docker.internal:3005
    routes:
      - name: booking-route
        paths:
          - /api/booking
        strip_path: false

  - name: payment
    url: http://host.docker.internal:3006
    routes:
      - name: payment-route
        paths:
          - /api/payment
        strip_path: false

  - name: analytics
    url: http://host.docker.internal:3007
    routes:
      - name: analytics-route
        paths:
          - /api/analytics
        strip_path: false
