name: linkbeet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  google_fonts: ^6.2.1

  # UI
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17

  # Media
  image_picker: ^1.1.2

  # Storage
  flutter_secure_storage: ^10.0.0

  # Dependency Injection
  get_it: ^9.2.0
  injectable: ^2.7.1+4

  # Navigation
  go_router: ^17.0.1

  # Internationalization
  intl: ^0.20.2

  # Logging
  logger: ^2.6.2

  # Storage
  shared_preferences: ^2.5.4
  pinput: ^6.0.1
  font_awesome_flutter: ^11.0.0
  modal_bottom_sheet: ^3.0.0

  # Location & Maps
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_map: any
  latlong2: any

  # Firebase
  firebase_core: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_flavorizr: ^2.4.1
  build_runner: ^2.4.14
  go_router_builder: ^4.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.4
  image: ^4.7.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/luncher/ios/AppIcon~ios-marketing.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/black-logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: "assets/images/native-splash-logo.png"
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true
  fullscreen: false

  android_12:
    image: "assets/images/native-splash-logo.png"
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#FFFFFF"

  web: false

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/luncher/
    - assets/svg/

flavorizr:
  ide: 'vscode'
  flavors:
    dev:
      app:
        name: 'LinkBeet Dev'
      android:
        applicationId: 'com.example.linkbeet.dev'
      ios:
        bundleId: 'com.example.linkbeet.dev'
      icon: 'assets/luncher/ios/AppIcon~ios-marketing.png'
      adaptive_icon_background: "#FFFFFF"
      adaptive_icon_foreground: "assets/images/black-logo.png"

    stage:
      app:
        name: 'LinkBeet Stage'
      android:
        applicationId: 'com.example.linkbeet.stage'
      ios:
        bundleId: 'com.example.linkbeet.stage'
      icon: 'assets/luncher/ios/AppIcon~ios-marketing.png'
      adaptive_icon_background: "#FFFFFF"
      adaptive_icon_foreground: "assets/images/black-logo.png"

    prod:
      app:
        name: 'LinkBeet'
      android:
        applicationId: 'com.example.linkbeet.app'
      ios:
        bundleId: 'com.example.linkbeet.app'
      icon: 'assets/luncher/ios/AppIcon~ios-marketing.png'
      adaptive_icon_background: "#FFFFFF"
      adaptive_icon_foreground: "assets/images/black-logo.png"
